config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :entries, only: [:new, :create]
  end
  root 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place

  validates :title, presence: true
  validates :description, presence: true
  validates :posted_on, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @place = Place.find(params[:place_id])
    @entry = @place.entries.new
  end

  def create
    @place = Place.find(params[:place_id])
    @entry = @place.entries.new(entry_params)
    if @entry.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :posted_on)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry for <%= @place.name %></h1>

<%= form_with model: [@place, @entry], local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :posted_on, "Date" %>
    <%= form.date_field :posted_on %>
  </div>
  <div>
    <%= form.submit 'Create Entry' %>
  </div>
<% end %>

<%= link_to 'Back to Place', place_path(@place) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places I've Been</h1>

<%= link_to 'Add New Place', new_place_path %>

<ul>
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place_path(place) %>
    </li>
  <% end %>
</ul>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with model: @place, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit 'Create Place' %>
  </div>
<% end %>

<%= link_to 'Back to Places', places_path %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>


<ul>
  <% @entries.each do |entry| %>
    <ul>
      <h2><%= entry.title %></h2>
       <p>(<%= entry.posted_on %>)</p>
      <p><%= entry.description %></p>
      
    </ul>
  <% end %>
</ul>

<%= link_to 'New Post', new_place_entry_path(@place) %>

<%= link_to 'All Places', places_path %>